#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libass
Version  : 0.15.0
Release  : 3
URL      : https://github.com/libass/libass/archive/0.15.0/libass-0.15.0.tar.gz
Source0  : https://github.com/libass/libass/archive/0.15.0/libass-0.15.0.tar.gz
Summary  : LibASS is an SSA/ASS subtitles rendering library
Group    : Development/Tools
License  : ISC
Requires: libass-lib = %{version}-%{release}
Requires: libass-license = %{version}-%{release}
BuildRequires : nasm-bin
BuildRequires : pkgconfig(fontconfig)
BuildRequires : pkgconfig(freetype2)
BuildRequires : pkgconfig(fribidi)
BuildRequires : pkgconfig(harfbuzz)
BuildRequires : pkgconfig(libpng)

%description
[![Build status](https://api.travis-ci.org/libass/libass.png)](https://travis-ci.org/libass/libass)

%package dev
Summary: dev components for the libass package.
Group: Development
Requires: libass-lib = %{version}-%{release}
Provides: libass-devel = %{version}-%{release}
Requires: libass = %{version}-%{release}

%description dev
dev components for the libass package.


%package lib
Summary: lib components for the libass package.
Group: Libraries
Requires: libass-license = %{version}-%{release}

%description lib
lib components for the libass package.


%package license
Summary: license components for the libass package.
Group: Default

%description license
license components for the libass package.


%prep
%setup -q -n libass-0.15.0
cd %{_builddir}/libass-0.15.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1605902051
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1605902051
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libass
cp %{_builddir}/libass-0.15.0/COPYING %{buildroot}/usr/share/package-licenses/libass/7b715718a08e1da65de75f83882b562e1b97b904
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/ass/ass.h
/usr/include/ass/ass_types.h
/usr/lib64/libass.so
/usr/lib64/pkgconfig/libass.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libass.so.9
/usr/lib64/libass.so.9.1.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libass/7b715718a08e1da65de75f83882b562e1b97b904
